### PR TITLE
Voice search for the iOS app

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
This PR contains changes for the initial voice search for the iOS app. I'd like for you to try out the TestFlight build # 81, and present your feedback.

These are some of the items which we should consider and hopefully add to this feature:
- Localized voice search: this initial implementation always uses English locale when performing the search + recognition. What we can do here is perform the recognition based on the user's phone locale. That practically means, if your phone is set to German locale, the speech recognition will expect German text, and we would use the CT search endpoint with the locale set to "de".
- Waveform for the input sound: show the waveform representing the input audio, similar to what Siri has. It is a nice way to give users some feedback on whether they're being listened to.
- Voice feedback for voice search: it could be nice to hear some spoken feedback after you've just said your search query.

### CODE REVIEW

**Comment by cneijenhuis** [comment]
The localization is really an issue if set to German, because many of the product description contain German words. We should fix it to work with the same locale we use for display.

Minor things:
- The keyboard opens after the search
- It doesn't scroll to the beginning of the search results when doing a new voice search in the middle of previous searches

Waveforms would be nice to have, as well as voice feedback.

**Comment by mmoelli** [comment]
Hey @nikola-mladenovic Really like the functionality, although I have the feeling, that the sorting is still not working properly. When you search for blue shirt, it seems that createdAt is still the primary sorting option. Once we use search terms, the app should discard sorting to enable the default sorting via relevance. When I try directly via Playground, the result is much better. 

Maybe we can incorporate this with a different PR.

Regarding the additional features:
* We could also think about using the locale stored with the customer account (which is currently not used in Sunrise). But in general I think the locale of the phone is a good idea. Although we should match it with the supported languages which are provided via /projects endpoint. 
* Waveforms are cool, but question is the needed effort to implement this.
* Same for voice feedback.

**Comment by nikola-mladenovic** [comment]
@mmoelli - looking at the code, you're right - we do set the `sort` parameter to `createdAt desc` when the user performs a search:
```
// Sort by newer first, but only when the user performs a text search
if text != "" {
    sort = ["createdAt desc"]
}
```
We can easily remove this (as a part of this PR). Would you like to completely remove the sort, or reverse the logic when it's used (i.e sort only when there's no search text specified)?


@cneijenhuis - Both things have been fixed in the latest commit, and will do a TestFlight build right together with the product sort update. 


Right after we merge this one, I shall proceed with the localized text speech - I guess at this point we can use the locale from the user's phone, because we use that across the app to display any attribute names / values, and any other API fields which are localized. We could also consider improving this with the option for the user to choose between the API locale or phone's. Also, an error message if the phone's locale isn't supported for a specific project will be displayed.

**Comment by mmoelli** [comment]
In general it would be great, if we could disable this, at least for the search results. By default, every search is sorted by relevance, if no sort param is given.

**Comment by nikola-mladenovic** [comment]
Let's disable it completely then - like you said, that will give us relevance sorting in return 👍

**Review by cneijenhuis — APPROVED** [review]

**Comment by nikola-mladenovic** [comment]
Incorporated sorting changes, you can check it out in the TestFlight build # 82, which should be available soon.

Going to merge this one, and proceed with the localized speech recognition search + localized POP universal link support.

Right after that will try to see if we could add the waveform + voice feedback in a reasonable time.

**Pull request merged**
