### PR TITLE
Closes #134 Show POP from the categories screen if there are no subcategories

### LINKED ISSUE #134: Show POP from the categories screen if there are no subcategories
Currently the categories screen need at least 3-level deep structure to show a POP from the categories screen.

Some of the demo use-cases would need to show a POP directly from the second category level.

The idea of this issue is to modify the categories screen logic, so that it presents the POP in case the 2nd level cat doesn't contain any subcategories.

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
TestFlight build # 69

### CODE REVIEW

**Comment by nikola-mladenovic** [comment]
@cneijenhuis - I've updated `CategoriesViewModel` to retrieve all categories in a single request (and synchronize retrieval properly in case we use the app in projects with over 500 cats).

**Comment by nikola-mladenovic** [comment]
After trying out the TestFlight build # 70, LMK whether you think we should keep or remove the loading indicator. I've added in case the categories request(s) last(s) long, but for our demo projects, that is really not the case, so it just appears and disappears quickly.

**Review by cneijenhuis — APPROVED** [review]

**Comment by cneijenhuis** [comment]
I actually don't notice the loading indicator at all 😉 

I think it's good to keep it, just in case network is unstable or so.

**Comment by nikola-mladenovic** [comment]
Actually the build # 70 with the current changes is available since a couple of mins ago - feel free to check it out if you get a chance.

**Pull request merged**
