### PR TITLE
Closes #132 Add Cart Checkout

### LINKED ISSUE #132: Cart Checkout
The customer should be able to perform a checkout from the cart tab. The existing _CHECKOUT NOW_ button should be used to start the checkout flow.

In case the customer has a default shipping (or billing) address it will be presented on the first checkout screen, with the following options:
- use the default address;
- choose one of the previously used addresses (each the customer checks out with a new address we shall store it using the _me_ endpoint);
- add a new address (the address input form will be shown).

The address input form should contain the same fields as on Sunrise web.

The next screen should show a list of shipping methods. The `shipping-methods` should be used to retrieve them.

Finally, the payment details section should show only one selectable option: _Prepaid_.

After the completing the the above flow, a new order shall be created.

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
Things that still need to be added to the cart checkout:
- Price for shipping methods;
- Add payment to the cart;
- New address form validation.

### CODE REVIEW

**Review by cneijenhuis — COMMENTED** [review]
Code looks good, waiting for a TestFlight release 😉

**Comment by nikola-mladenovic** [comment]
TestFlight build # 72 has been processed

**Comment by nikola-mladenovic** [comment]
Addressed PR remarks, TestFlight build # 73

**Review by cneijenhuis — APPROVED** [review]
Great work :1st_place_medal:

**Comment by nikola-mladenovic** [comment]
Removed continue shopping button from the cart overview 👍

**Pull request merged**
