### PR TITLE
Closes #89 Add store selection screen

### LINKED ISSUE #89: Create Store Selection Screen
Similar UI to find my iPhone app. We want to have a list of stores underneath the map, and tapping on any store would lead to store details screen.

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
After tapping on _MY STORE_ on the account / preferences screen, you get a list of stores underneath the map, and tapping on any store expands the map, and shows store address and opening hours in the bottom of the screen. Tapping on the bottom of the screen will lead you to the store details screen (we got the design for https://github.com/commercetools/commercetools-sunrise-ios/issues/90).

On the store details screen (https://github.com/commercetools/commercetools-sunrise-ios/issues/90) we will be able to actually select the store to be _preferred_ or _my store_. The checkmark you currently see on the store selection list is just hardcoded to the nearest store, but once store details are in place, it'll show the store you selected.

As for the initial map zoom region, the way I implemented:
- it shows the region which fits both user location and the selected (for now the nearest) store;
- in case the user location isn't available, map zooms out, so all stores fit the map view.

@cneijenhuis @lauraluiz - feel free to suggest something else if you think it'd look better 😊

### CODE REVIEW

**Comment by nikola-mladenovic** [comment]
TestFlight build 55 is available.

**Comment by cneijenhuis** [comment]
The initial zoom looks good to me, code as well!

I found it a bit counter-intuitive that to go back from the store details to the stores list, I had to press `Done` (on the right) and could not use the `<` (on the left). WDYT?

Also, nothing happens when I click on the red pin of a store - I would expect that the store details open?

**Comment by nikola-mladenovic** [comment]
We're now storing channel ID for the _my store_ customer selects in a `myStore` custom type.

Navigation from the full screen map, back to the split screen list that contains both map and the list of stores is implemented via standard back button, while keeping the nice animation.

**Comment by nikola-mladenovic** [comment]
While working on https://github.com/commercetools/commercetools-sunrise-ios/issues/91 and https://github.com/commercetools/commercetools-sunrise-ios/issues/93 I've noticed we don't have a way to _deselect_.

We can have add a smaller cell on top of the store list, right below the map view, which says something like _Shop Online_, and that would in fact, deselect any store user has previously selected.
The other option would be to add a button on the right side side of the navigation bar (similar to how our Logout button looks). @cneijenhuis WDYT?

**Comment by cneijenhuis** [comment]
I guess the logout button on the right sounds better to me - but maybe @mmoelli can chime in?

I'm also not sure whether we'd like to deselect at all or whether on the PDP/POP we should switch between Online/MyStore?

**Comment by nikola-mladenovic** [comment]
> I'm also not sure whether we'd like to deselect at all or whether on the PDP/POP we should switch between Online/MyStore?

That makes sense to me. If that's what we want to do here, I'd suggest to merge this PR, and add this feature to https://github.com/commercetools/commercetools-sunrise-ios/pull/125 ?

**Comment by mmoelli** [comment]
@cneijenhuis @nikola-mladenovic I wouldn't use the logout button here as probably want to use your addresses also for the normal online shopping. The reservations are usually addon features and not the core of the application. I would also love to see 2 options on the PDP meaning "either you pick it up, or you have sent it home"

For the POP we should indeed have a switch to change Store/Online catalog as they could differ heavily. But I have no opinion here where to put it.

**Comment by cneijenhuis** [comment]
Brainstorming results with @mmoelli:
On the POP, if the top-bar "Sunrise Store Foobar" or "Online Store" is tapped, an Alert View with 3 options is displayed: 
* "Select Online Store"
* "Select Store Foobar" (= My Store)
* "Change My Store"

Once set, the "My Store" can not be unset. WDYT?

Also, the navigation/selection inside the "My Store" view was not intuitive for Martin. It's not clear that after the store has been selected from the list, one has to tap on the lower screen to be able to select it as "My Store". We could 
* jump directly from the list into the fullscreen-view of the store
* add buttons into the lower-screen (i.e. "Select as my store" "More Details")
* implement a pull-up-for-full-screen (don't know what this pattern is called exactly, but it's what Apple Maps and Google Maps does)

What would you prefer?

**Comment by nikola-mladenovic** [comment]
> On the POP, if the top-bar "Sunrise Store Foobar" or "Online Store" is tapped, an Alert View with 3 options is displayed:
"Select Online Store"
"Select Store Foobar" (= My Store)
"Change My Store"
Once set, the "My Store" can not be unset.

Absolutely agree 👍 


> jump directly from the list into the fullscreen-view of the store

The easiest thing to do, but then we ditch the animation and the transition we have from the store list, to the full screen map. @mmoelli - how nice does this look to you, would you like to keep it?

> add buttons into the lower-screen (i.e. "Select as my store" "More Details")

Depending on whether we want to keep the _lower-screen_ / _full screen map_, I'd say this would be the most intuitive way to show it.

**Comment by nikola-mladenovic** [comment]
I've incorporated changes regarding active store selection on the POP, as a part of https://github.com/commercetools/commercetools-sunrise-ios/pull/125

**Pull request merged**
