### PR TITLE
Closes #91 Update POP with my store selection

### LINKED ISSUE #91: Update POP with my store selection
On top of all product we want to have a cell showing selected store (if any is selected at the moment, or "online" shopping if not), and by tapping on that cell, we take the user to the store selection screen.

When performing a search with a store preselected, we want to show only those items with `onStock=true` for the selected channel, as described in:
http://dev.commercetools.com/http-api-projects-products-search.html#filter-by-product-variant-availability

Also, the price show in the product cell on POP, should match the one set for the particular channel, if a store is selected.

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
- [x] On top of all product we want to have a cell showing selected store (if any is selected at the moment, or "online" shopping if not), and by tapping on that cell, we take the user to the store selection screen.
- [x] When performing a search with a store preselected, we want to show only those items with onStock=true for the selected channel
- [x] Prices show in the product cell on POP, should match the one set for the particular channel, if a store is selected.

This PR should be merged after https://github.com/commercetools/commercetools-sunrise-ios/pull/124

### CODE REVIEW

**Comment by cneijenhuis** [comment]
Code LGTM. Is there a TestFlight release for it yet?

**Comment by nikola-mladenovic** [comment]
I'm also including https://github.com/commercetools/commercetools-sunrise-ios/issues/93 changes here, and TestFlight # 57 contains all those changes.

- [x] When the user reaches PDP from a POP having a store selected, we want to show customized price, variants available only to that particular channel, and hide the Add to Bag button.
- [x] The reserve button should make the reservation without showing the store selection screen, use the users preselected store.

**Comment by nikola-mladenovic** [comment]
I've added tests to cover showing channel specific variants, prices, and attributes on POP and PDP.

**Comment by nikola-mladenovic** [comment]
TestFlight build # 59

**Pull request merged**
