### PR TITLE
Add German locale to the iOS app

### PR DESCRIPTION
**Pull request by nikola-mladenovic**
Many thanks to @nkuehn for doing the German translation 🎉 

TestFlight build # 89 contains the translations, so you can all check it out and give feedback 👍

### CODE REVIEW

**Comment by nkuehn** [comment]
I tried the app and found quite a bunch of things where the german translation does not fit the space and sometimes content is still english.  
Do you want to test and tell me the places to fix? 

I can try, but have no time before friday or so.

**Comment by nikola-mladenovic** [comment]
Right now, I only see the "View" button doesn't fit (on the my account page, when expanding my orders or reservations). I'm using iPhone SE, which has the lowest screen width. Which one are you using?

**Comment by nkuehn** [comment]
I have a 5S, which is also the small screen. 

But I'm also not happy with some of the text I did - does not feel right in the places where it appears now. 

OK for now but I'd prefer to do an iteration before we release to non-testers.   Can you create a fresh XLIFF including the existing german translation so I can fix some stuff?

**Comment by nikola-mladenovic** [comment]
I've sent you the latest German translation, whenever you get a chance 👍

**Review by cneijenhuis — APPROVED** [review]
Code is fine, but I won't have time to review all the translations.

**Comment by nikola-mladenovic** [comment]
I've just pushed a couple of minor changes, mostly adding a few missing translations for the rich notification interface:

```
/* View */
"View" = "Ansehen";

/* Get Directions */
"Get Directions" = "Anfahrt";
```

Hope I got it right @nkuehn?  😊 

Also, I extended the _View_ / _Ansehen_ button on the my account screen, which wasn't wide enough for _Ansehen_ to fit.

**Comment by nikola-mladenovic** [comment]
The latest stuff's in TF build # 90

**Comment by nkuehn** [comment]
Here you go with an updated version that tries to avoid a few texts that are too long and removes some inconsistencies. 

[de_reviewed.xliff.zip](https://github.com/commercetools/commercetools-sunrise-ios/files/1021351/de_reviewed.xliff.zip)

Just the "REserve" Button in the stores list is an issue, there's just not enough width available in my iPhone 5S.

**Comment by nikola-mladenovic** [comment]
The latest push contains improvements from Nikolaus, small modifications for the store selection screen + translation for the reservation push notification.

This is the payload sent from the IronWorker:
```
{
  "aps":{
    "alert":{
      "loc-key":"RESERVATION_READY",
      "body":"Hello, your item is ready for pickup."
    },
    "category":"reservation_confirmation"
  },
  "reservation-id":"${payload.order.id}"
}
```

In case the customer phone's language is set to German, the iOS will look up the German translation with the `RESERVATION_READY` key from the `Localizable.strings` file.
In case the customer phone's language is not set to German, it will just use the english title, included in the payload.

These changes are incorporated in TF build 91, which should be available shortly.

**Comment by nkuehn** [comment]
Very nice now! 

P.S.: I found two strings that I cannot translate at all (or did not find in the XLIFF):  In "My account", when you open the "my orders" list the table has haeders "oder number" and "order total".  These are still in english.  They are not well-aligned anyways, I personally could live with removing them altogether.

**Review by nkuehn — APPROVED** [review]
see last comment for a thing that is not translatable, but for the actual translation I'm happy now.

**Comment by nikola-mladenovic** [comment]
Ah, those two are located in a separate .xib file which we haven't localized.
Since we translated everything else I think we should either a) remove these or b) if @nkuehn can give me the translations it'd be a min to incorporate them.

Whatever you decide 👍

**Comment by nkuehn** [comment]
@mmoelli  is "the boss" for UI changes :-)  (see above)

**Comment by mmoelli** [comment]
@nikola-mladenovic looks good. 

Regarding the two mentioned missing translations:
- "Order Number" => "Bestellnummer"
- "Order Total" => "Gesamtpreis"

Thanks!

**Review by mmoelli — APPROVED** [review]

**Comment by nikola-mladenovic** [comment]
Thanks @mmoelli ! 👍

**Pull request merged**
